platform :ios, '7.0'

inhibit_all_warnings!

xcodeproj 'TDD Workshop'

pod 'Parse-iOS-SDK', '~> 1.2'

target :specs do
  link_with 'TDD WorkshopTests'

  pod 'Specta'
  pod 'Expecta'
  pod 'OCMockito'
  pod 'OCMock'
end
